POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa28iLCJpZCI6IjVmMmQwNGVhOGVmODc1NDdkYzYwZTE0NCIsImlhdCI6MTU5Njc4NjAyOX0.mzK8DWOq2Rumb35MQIsl88KB4MwK21JUlkQ9H9m1FpE

{
    "title": "Blog made after creating middleware",
    "author": "Mluukksi",
    "url": "Url1",
    "likes": 1,
    "userId": "5f2d04ea8ef87547dc60e144"
}